### ISSUE TITLE
Streaming example?

### ISSUE THREAD

**Issue by korczis** [turbo/js#13]
Is it possible to continuously stream the data to shader/turbo and continuously consume results? 

Can you provide some example, please?

**Comment by turbo** [comment]
Technically possible, but not without substantial modification to the code. Keep in mind that a continuous load will always block the page if it exceeds the capabilities of the GPU. That limits how complex the operation can actually be.

Can you give me a specific use case? Then I might create an example and think about how this could be integrated into future versions.
