### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by amilajack** [turbo/js#14]
would be great if this could be packaged as an npm package

**Comment by turbo** [comment]
I've added a placeholder for now at https://www.npmjs.com/package/turbojs

If you need to use this in node or require anything else from the package (in terms of #11), don't hesitate to make a PR.

**Comment by amilajack** [comment]
So i can install with npm and it should work correctly?

**Comment by msimpson** [comment]
@amilajack 
I've just created a PR (#15) which addresses this usage. Once it's merged, you should be able to pull this down via NPM and use it with things like Browserify and Babel.
