### ISSUE TITLE
canvas.getContext not working

### ISSUE THREAD

**Issue by septs** [turbo/js#16]
```
> canvas = document.createElement('canvas')
< <canvas>​
> canvas.getContext('experimental-webgl')
< null
> canvas.getContext('experimental-webgl2')
< null
> canvas.getContext('webgl')
< null
> canvas.getContext('webgl2')
< null
```

**Comment by turbo** [comment]
Well, then your browser doesn't support WebGL. It would be nice if you could add browser and hardware details to this issue. As of now, there's nothing I can do with this info.

**Comment by septs** [comment]
Just install the system may not be loaded graphics driver

**Comment by septs** [comment]
I think we can add an `isSupported` API

**Comment by turbo** [comment]
I've added a new exception for failed inits. Catch that for extended support testing.
