### ISSUE TITLE
Are these matrix operations supported? 

### ISSUE THREAD

**Issue by TheInvoker** [turbo/js#19]
Hi, does your library support doing these matrix operations? Note all the dimensions will be known on runtime.

![capture1](https://cloud.githubusercontent.com/assets/5560751/23228619/3dbcbe28-f90b-11e6-813f-fb044f145657.PNG)
![capture2](https://cloud.githubusercontent.com/assets/5560751/23228620/3dc64fb0-f90b-11e6-9e9c-23152e8c294e.PNG)
![capture3](https://cloud.githubusercontent.com/assets/5560751/23228621/3dc89630-f90b-11e6-8e82-447c44338af3.PNG)

**Comment by turbo** [comment]
The library isn't what's running the code. The kernels are written in GLSL, a subset of C. You can read about what operations are supported on vectors of 1 to 4 dimensions [here](https://en.wikibooks.org/wiki/GLSL_Programming/Vector_and_Matrix_Operations).

**Comment by TheInvoker** [comment]
Can you explain further, I'm new to this and not understanding.

**Comment by turbo** [comment]
I can't teach you C or GLSL. I've linked the documentation. Please read the full docs if you are new to GLSL.

**Comment by TheInvoker** [comment]
Are you saying that the only operations that are supported is the ones that GLSL can do?

**Comment by turbo** [comment]
Nothing is "supported" or "not supported". This library simply run GLSL code and handles data I/O for you. The rest is up to you.

**Comment by TheInvoker** [comment]
So you are saying that to do the matrix operations I want, I just have to use the operations that GLSL provides to build the operations I want?
