### ISSUE TITLE
Ubuntu / iGPU: Ah snap

### ISSUE THREAD

**Issue by andreapaiola** [turbo/js#2]
Ah snap! There was no error compiling the test kernel or running it, but the numbers don't check out. Please report your browser (+ version) and hardware configuration to us, so we can try to fix this. Deviation was 0.3373333334457129.
console:
Values are: 0.00900000031106174 and 1.0210000006482005

Chrome on Ubuntu 14.04 64 bit on Intel NUC i3-4010U

**Comment by andreapaiola** [comment]
Deviation was 0.020666667027398944.

Values are:
0.0020000000949949026
and
0.06400000117719173

on Firefox Developer Edition 51.0a2 (2016-10-17) (64-bit)

**Comment by turbo** [comment]
Moved to #1
