### ISSUE TITLE
Multiple inputs

### ISSUE THREAD

**Issue by avinoamr** [turbo/js#28]
Hi.

Currently turbo.js is limited to only unary operations - mapping the same single input value. I find many cases where I might need multiple inputs. For example: element-wise addition, multiplication, exponentiation, etc.

I've managed to create a new API that supports this use-case, by creating multiple textures - one per input. For example:

```js
var y = turbo.run({x1: data, x2: data}, `
    void main(void) {
        commit(read(x1) + read(x2));
    }
`)
```

Basically, the input to `run()` is used to build multiple, equally-sized textures that are then referenced with the same names in the shader code. There's an overloaded read function: `vec4 read(sampler2D t)`.

I have most of the code ready and working, and willing to open a PR - but before I spend too much time on it, I wanted to see if there's interest in such a thing and is this new API sufficient? If yes - which branch would you prefer that I merge into? dev or master?

Thanks.

**Comment by avinoamr** [comment]
Another idea for the API is to have the named inputs compiled as the lookup function:

```void main(void) {
    commit(x1() + x2());
}```

Thoughts?

**Comment by avinoamr** [comment]
Is this repo still actively maintained? Anyone knows?

**Comment by shiyeling** [comment]
@avinoamr
Actually I have same question. I guess the maintainer may be too busy to keep moving this forward.

**Comment by ahmetfaslantas** [comment]
Probably not last push was 3 years ago

**Comment by turbo** [comment]
>Is this repo still actively maintained?

It isn't. I recommend using gpgpu.js.

**Comment by foo123** [comment]
@avinoamr  I am interested in this feature. I cant seem to find the code in your repositories. Possible to share? Thanks!
