### ISSUE TITLE
Is this repo still actively maintained?

### ISSUE THREAD

**Issue by avinoamr** [turbo/js#29]
I see some issues are unaddressed for months. My own opened issue has been untouched for 11 days now. If it's not maintained, I'd be happy to take over as this is a really great library. Worst case, if there's interest, we can fork it and go forward.

**Comment by cellvia** [comment]
Definitely interested, also do you know of alternative libraries to look at?

**Comment by turbo** [comment]
If you need a general purpose library, look at GPU.js.
