### ISSUE TITLE
Ah snap! error

### ISSUE THREAD

**Issue by franciscop** [turbo/js#3]
I also got an error:

> Ah snap! There was no error compiling the test kernel or running it, but the numbers don't check out. Please report your browser (+ version) and hardware configuration to us, so we can try to fix this. Deviation was 10220674220032.67

The meter shows a 0.98 *improvement*

On the console:

```
Values are:
-30662022660096
and
2.012000000104308
```

My Software/Hardware:

Firefox 49.0.2
Ubuntu 16.04
Zenbook UX305CA
Processor: Intel® Core™ m3-6Y30 CPU @ 0.90GHz × 4
Graphics: Intel® HD Graphics 515 (Skylake GT2) 

Another note: I've successfully used web workers to x4 the performance, but that's just for the CPU and not the GPU. A fallback would be nice though (:

**Comment by turbo** [comment]
Moved to #1
