### ISSUE TITLE
inprovements

### ISSUE THREAD

**Issue by strangerintheq** [turbo/js#32]
recently i was modified code of turbo.js to support webgl2 and render one triangle instead of two like in my gist https://bl.ocks.org/strangerintheq/27b8fc4e53432d8b9284364713ce8608 and it was runs faster than webgl version, here is average result for measures 50x in ms:

webgl2 : 10.45
webgl: 36.96
cpu: 290.04

if you interested with this updates i can create pull request, version with two triangles already in my fork of your repo, full screen trialgle code is not ready yet

**Comment by turbo** [comment]
What's the browser support for webgl2?

**Comment by strangerintheq** [comment]
i dont know, but i sure that is not important, i want to computations done as soon as possible,  if browser support webgl2 it runs using it, if no it fallbacks to webgl1 implementation

**Comment by strangerintheq** [comment]
in my version i also separated creation of shader program from performing computaions

js call looks like 

turbojs.build('shader code')(data);

this approach gives me ability to perform different computations with one shader, instead of creation of shader every call

and keep support for backward-compatibility
 

ps: rendering of one full screen triangle possible with lesser bindings from cpu to gpu, or with using built-in vertex_id attribute it possible without using any cpu-gpu buffer, and this approach more efficient because when you rendering two triangles there are overlapping pixels on its edges processed twice.


sorry for my english plz

**Comment by turbo** [comment]
Create a PR please.
