### ISSUE TITLE
Ah snap! Deviation: 0.3396666668898737.

### ISSUE THREAD

**Issue by kritixilithos** [turbo/js#6]
In the https://turbo.github.io website, under the JAVASCRIPT & TURBO.JS section, I got an "Ah snap!" error message with deviation of `0.6786666667709748`

In my JavaScript console, I got the following message:

    Values are:
    -0.010000000707805157
    and
    2.0259999996051192

Browser: Google Chrome Version 54.0.2840.87 (64-bit)
Hardware: MacBook Air (early 2014)
Processor: 1.4 GHz Intel Core i5
Memory: 4 GB 1600 MHz DDR3
Graphics: Intel HD Graphics 5000 1536 MB
Software: OS X El Capitan 10.11.4

**Comment by turbo** [comment]
Moved to #1
