### ISSUE TITLE
Add example for the lazy

### ISSUE THREAD

**Issue by pannous** [turbo/js#7]
"How to use":
```
<script src="https://raw.githubusercontent.com/turbo/js/master/turbo.js"/>
<script>
// example
</script>
```

**Comment by turbo** [comment]
Example 1 is a complete walk-through. The last codeblock contains the example code in it's entirety. I assume that users know how to include a script in an HTML file.

But a sandbox-ish, gallery-ish collection of examples is coming at some point. If you have a concrete example of how such an example should be integrated, don't hesitate to submit a PR.

**Comment by turbo** [comment]
If you are going to do this, please only use this URL for loading turbo.js:

``` txt
https://turbo.github.io/js/turbo.js
```
