### ISSUE TITLE
Linux/Quadro, Performance overestimation error

### ISSUE THREAD

**Issue by pmontrasio** [turbo/js#8]
Ubuntu 16.04, Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz, nvidia quadro K1100M.

FF 49.0.2.
Pure JS is always 1.44. Turbo has been at about 9.5/10.0 for a long number of reloads.

Then I opened Chrome 54.0.2840.90 to benchmark in there. Pure JS is always at 1.38/1.14 but Turbo is only at around 2.6/3.3.

Now Turbo in FF stays at the same level. Did it somewhat used up resources in the GPU and slowed it down?

**Comment by turbo** [comment]
The 10.0 (that would be 40,000 \* 32bit per ms) is probably wrong. 1.14 to 2.6 sounds like the right ratio.

Even then it's surprising this works on your linux install at all. So a small glitch, but nothing that should cause any hard math errors.
