### ISSUE TITLE
Ah snap!

### ISSUE THREAD

**Issue by ghost** [turbo/js#9]
Ah snap! There was no error compiling the test kernel or running it, but the numbers don't check out. Please report your browser (+ version) and hardware configuration to us, so we can try to fix this. Deviation was 137920146396501.34.

Chromium Version 53.0.2785.143 Built on Ubuntu , running on LinuxMint 18 (64-bit)
Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Intel® HD Graphics 530

Let me know if you need anything else!

**Comment by turbo** [comment]
Please read the issues before opening a new one. Moved to #1.
